
keys = {"PIE_MENU": [{"label": "3D View",
                      "keymap": "Object Mode",
                      "idname": "machin3.call_decal_pie",
                      "type": "D",
                      "value": "PRESS",
                      "properties": [("idname", "decal_machine")]}],
        "QUICK_INSERT": [{"label": "3D View",
                          "keymap": "Object Mode",
                          "idname": "machin3.call_decal_operator",
                          "type": "D",
                          "value": "PRESS",
                          "ctrl": True,
                          "properties": [("idname", "quick_insert_decal"),
                                         ("isinvoke", True)]}],
        "SELECT": [{"label": "3D View",
                    "keymap": "Object Mode",
                    "idname": "machin3.select_decals",
                    "type": "LEFTMOUSE",
                    "value": "DOUBLE_CLICK",
                    "info": ["For multiple objects, double-click in the background", "Users of the 2.80 keymap and users selecting with RIGHTMOUSE: consider remapping this"]}],
        }
