# proxe's defaults
defaults = {
    'name panel': {
        'location': 'UI',
        'pin active object': True,
        'pin active bone': True,
        'hide find': False,
        'hide replace': True,
        'filters': False,
        'shortcuts': False,
        'display names': False,
        'search': '',
        'clear search': True,
        'regex': False,
        'mode': 'LAYERS',
        'groups': True,
        'action': True,
        'grease pencil': True,
        'constraints': True,
        'modifiers': True,
        'bone groups': True,
        'bone constraints': True,
        'vertex groups': True,
        'shapekeys': True,
        'uvs': True,
        'vertex colors': True,
        'materials': True,
        'textures': True,
        'particle systems': True,
        'bone mode': 'LAYERS',
        'display bones': False,
    },

    'properties panel': {
        'location': 'UI'
    },

    'shared': {
        'large popups': True,
        'sort': True,
        'type': 'ALPHABETICAL',
        'axis': 'X',
        'invert': False,
        'count': True,
        'link': False,
        'pad': 1,
        'start': 1,
        'step': 1,
        'separator': '_',
        'ignore': False
    },

    'auto name': {
        'mode': 'SELECTED',
        'objects': False,
        'constraints': True,
        'modifiers': True,
        'object data': False,
        'bone constraints': True,
        'object type': 'ALL',
        'constraint type': 'ALL',
        'modifier type': 'ALL',

        'object names': {
            'prefix': True,
            'mesh': 'geo_',
            'curve': 'crv_',
            'surface': 'sfc_',
            'meta': 'mta_',
            'font': 'txt_',
            'armature': 'rig_',
            'lattice': 'lat_',
            'empty': 'ept_',
            'speaker': 'spk_',
            'camera': 'cam_',
            'lamp': 'lmp_',
        },

        'constraint names': {
            'prefix': False,
            'camera solver': 'camera_solver',
            'follow track': 'follow_track',
            'object solver': 'object_solver',
            'copy location': 'copy_location',
            'copy rotation': 'copy_rotation',
            'copy scale': 'copy_scale',
            'copy transforms': 'copy_transforms',
            'limit distance': 'limit_distance',
            'limit location': 'limit_location',
            'limit rotation': 'limit_rotation',
            'limit scale': 'limit_scale',
            'maintain volume': 'maintain_volume',
            'transform': 'transform',
            'clamp to': 'clamp_to',
            'damped track': 'damped_track',
            'inverse kinematics': 'inverse_kinematics',
            'locked track': 'locked_track',
            'spline inverse kinematics': 'spline_inverse_kinematics',
            'stretch to': 'stretch_to',
            'track to': 'track_to',
            'action': 'action',
            'child of': 'child_of',
            'floor': 'floor',
            'follow path': 'follow_path',
            'pivot': 'pivot',
            'rigid body joint': 'rigid_body_joint',
            'shrinkwrap': 'shrinkwrap',
        },

        'modifier names': {
            'prefix': False,
            'data transfer': 'data_transfer',
            'mesh cache': 'mesh_cache',
            'normal edit': 'normal_edit',
            'uv project': 'uv_project',
            'uv warp': 'uv_warp',
            'vertex weight edit': 'vertex_weight_edit',
            'vertex weight mix': 'vertex_weight_mix',
            'vertex weight proximity': 'vertex_weight_proximity',
            'array': 'array',
            'bevel': 'bevel',
            'boolean': 'boolean',
            'build': 'build',
            'decimate': 'decimate',
            'edge split': 'edge_split',
            'mask': 'mask',
            'mirror': 'mirror',
            'multiresolution': 'multiresolution',
            'remesh': 'remesh',
            'screw': 'screw',
            'skin': 'skin',
            'solidify': 'solidify',
            'subdivision surface': 'subdivision_surface',
            'triangulate': 'triangulate',
            'wireframe': 'wireframe',
            'armature': 'armature',
            'cast': 'cast',
            'corrective smooth': 'corrective_smooth',
            'curve': 'curve',
            'displace': 'displace',
            'hook': 'hook',
            'laplacian smooth': 'laplacian_smooth',
            'laplacian deform': 'laplacian_deform',
            'lattice': 'lattice',
            'mesh deform': 'mesh_deform',
            'shrinkwrap': 'shrinkwrap',
            'simple deform': 'simple_deform',
            'smooth': 'smooth',
            'warp': 'warp',
            'wave': 'wave',
            'cloth': 'cloth',
            'collision': 'collision',
            'dynamic paint': 'dynamic_paint',
            'explode': 'explode',
            'fluid simulation': 'fluid_simulation',
            'ocean': 'ocean',
            'particle instance': 'particle_instance',
            'particle system': 'particle_system',
            'smoke': 'smoke',
            'soft body': 'soft_body',
        },

        'object data names': {
            'prefix': False,
            'mesh': 'mesh',
            'curve': 'curve',
            'surface': 'surface',
            'meta': 'meta',
            'font': 'text',
            'armature': 'armature',
            'lattice': 'lattice',
            'empty': 'empty',
            'speaker': 'speaker',
            'camera': 'camera',
            'lamp': 'lamp',
        },
    },

    'batch name': {
        'mode': 'SELECTED',
        'actions': False,
        'action groups': False,
        'grease pencil': False,
        'pencil layers': False,
        'objects': False,
        'groups': False,
        'constraints': False,
        'modifiers': False,
        'object data': False,
        'bone groups': False,
        'bones': False,
        'bone constraints': False,
        'vertex groups': False,
        'shapekeys': False,
        'uvs': False,
        'vertex colors': False,
        'materials': False,
        'textures': False,
        'particle systems': False,
        'particle settings': False,
        'object type': 'ALL',
        'constraint type': 'ALL',
        'modifier type': 'ALL',
        'sensors': False,
        'controllers': False,
        'actuators': False,
        'line sets': False,
        'linestyles': False,
        'linestyle modifiers': False,
        'linestyle modifier type': 'ALL',
        'scenes': False,
        'render layers': False,
        'worlds': False,
        'libraries': False,
        'images': False,
        'masks': False,
        'sequences': False,
        'movie clips': False,
        'sounds': False,
        'screens': False,
        'keying sets': False,
        'palettes': False,
        'brushes': False,
        'nodes': False,
        'node labels': False,
        'frame nodes': False,
        'node groups': False,
        'texts': False,
        'ignore action': False,
        'ignore grease pencil': False,
        'ignore object': True,
        'ignore group': False,
        'ignore constraint': False,
        'ignore modifier': False,
        'ignore bone': False,
        'ignore bone group': False,
        'ignore bone constraint': False,
        'ignore object data': True,
        'ignore vertex group': False,
        'ignore shapekey': False,
        'ignore uv': False,
        'ignore vertex color': False,
        'ignore material': False,
        'ignore texture': False,
        'ignore particle system': False,
        'ignore particle setting': False,
        'custom': '',
        'insert': False,
        'insert at': 0,
        'find': '',
        'regex': False,
        'find only': True,
        'replace': '',
        'on found': True,
        'prefix': '',
        'suffix': '',
        'suffix last': False,
        'trim start': 0,
        'trim end': 0,
        'cut start': 0,
        'cut amount': 0,
    },

    'copy name': {
        'mode': 'SELECTED',
        'source': 'OBJECT',
        'objects': False,
        'object data': True,
        'materials': False,
        'textures': False,
        'particle systems': False,
        'particle settings': False,
        'use active object': False,
    },
}
