
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.18.0'
version_full = '5282a37619286624edbef830e1eda38b5c9469f6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

