

classes = {"CORE": [("ui.UILists", [("DecalLibsUIList", "")]),
                    ("properties", [("DecalLibsCollection", ""),
                                    ("DecalScalesCollection", ""),
                                    ("ExcludeCollection", "")]),
                    ("preferences", [("DECALmachinePreferences", "")]),
                    ("ui.operators.call_operator", [("CallDecalOperator", "call_decal_operator")]),
                    ("ui.operators.help", [("GetSupport", "get_decalmachine_support")]),
                    ("operators.libraries", [("Move", "move_decal_library"),
                                             ("Clear", "clear_decal_library"),
                                             ("Rename", "rename_decal_library"),
                                             ("Reload", "reload_decal_libraries"),
                                             ("Remove", "remove_decal_library"),
                                             ("ResetDecalsLocation", "reset_decals_location")]),
                    ("operators.pil", [("InstallPIL", "install_pil"),
                                       ("InstallPILAdmin", "install_pil_admin"),
                                       ("EasyInstallPILAdmin", "easy_install_pil_admin"),
                                       ("PurgePIL", "purge_pil")]),
                    ("properties", [("DecalSceneProperties", ""),
                                    ("DecalObjectProperties", ""),
                                    ("DecalMaterialProperties", ""),
                                    ("DecalImageProperties", ""),
                                    ("DecalCollectionProperties", "")])],

           "PIE_MENU": [("ui.pies", [("PieDecalMachine", "decal_machine")]),
                        ("ui.operators.scale", [("StoreIndividualDecalScale", "store_individual_decal_scale"),
                                                ("ClearIndividualDecalScale", "clear_individual_decal_scale"),
                                                ("Reset", "reset_decal_scale"),
                                                ("Set", "set_decal_scale")]),
                        ("ui.operators.call_pie", [("CallDecalPie", "call_decal_pie")])],

           "PANEL": [("ui.panels", [("PanelDECALmachine", "decal_machine")]),
                     ("ui.operators.match_material", [("UpdateMatchMaterials", "update_match_materials")]),
                     ("ui.operators.infotext", [("ResetOffsetPadding", "reset_infotext_offset_padding")])],

           "PANEL_CREATE": [("ui.panels", [("PanelDecalCreation", "decal_creation")])],
           "PANEL_UPDATE_LEGACY": [("ui.panels", [("PanelUpdateLegacyDecalLibraries", "update_legacy_decal_libraries")])],
           "PANEL_DEBUG": [("ui.panels", [("PanelDebug", "debug_decal_machine")])],
           "PANEL_HELP": [("ui.panels", [("PanelHelp", "help_decal_machine")])],


           "INSERTREMOVE": [("operators.insert_remove", [("Insert", "insert_decal"),
                                                         ("Remove", "remove_decal"),
                                                         ("QuickInsert", "quick_insert_decal")])],
           "VALIDATE": [("operators.validate", [("Validate", "valdate_decal")])],
           "ADJUST": [("operators.adjust", [("Adjust", "adjust_decal")])],
           "REAPPLY": [("operators.reapply", [("ReApply", "reapply_decal")])],
           "PROJECT": [("operators.project", [("Project", "project_decal"),
                                              ("UnShrinkwrap", "unshrinkwrap_decal")])],
           "SLICE": [("operators.slice", [("Slice", "slice_decal")]),
                     ("operators.gpanel", [("GPanel", "gpanel")])],
           "GETBACKUP": [("operators.get_backup", [("GetBackup", "get_backup_decal")])],
           "UNWRAP": [("operators.unwrap", [("Unwrap", "panel_decal_unwrap")])],
           "MATCH": [("operators.match", [("Match", "match_material")])],
           "SELECT": [("operators.select", [("Select", "select_decals")])],

           "CREATE": [("operators.create", [("Create", "create_decal"),
                                            ("LoadImages", "load_images"),
                                            ("ClearImages", "clear_images"),
                                            ("LoadFonts", "load_fonts"),
                                            ("ClearFonts", "clear_fonts"),
                                            ("AddDecalToLibrary", "add_decal_to_library"),
                                            ("UpdateLegacyDecalLibrary", "update_legacy_decal_library")])],

           "ADDON": [("operators.addon", [("GroupProDissolve", "grouppro_dissolve")])],

           "DEBUG": [("operators.debug", [("FixTexturePaths", "fix_decal_texture_paths"),
                                          ("FixLegacyNormals", "fix_legacy_normals"),
                                          ("ReRenderThumbnails", "rerender_decal_thumbnails"),
                                          ("UpdateNodeTree", "update_decal_node_tree"),
                                          # ("DebugWhatever", "debug_whatever"),
                                          ("ReplaceMaterial", "replace_material"),
                                          ("SetPropsAndNameFromMaterial", "set_props_and_name_from_material"),
                                          ("UpdateDecalBackup", "update_decal_backup"),
                                          ("DebugToggle", "decalmachine_debug")])],
           }
