
# imports
import os
import sys

# main
def main(defaults):

  # filepath
  filepath = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'defaults.py'))
  with open(filepath, 'r+') as default:
    default.truncate()
    default.write('# Generated by scripts.function.preferences.generate.main\n' + 'defaults = ' + str(defaults))
