defaults = {
    'amount': 10,
    'width': 1.0,
    'height': 2.0,
    'depth': 0.25,
    'uniform': True,
    'length_x_min': 0.25,
    'length_x_max': 0.75,
    'length_y_min': 0.25,
    'length_y_max': 0.75,
    'thickness_min': 0.01,
    'thickness_max': 0.05,
    'straight': 40,
    'decoration': 30,
    'split': 30,
    'bevel': 100,
    'bevel_size': 10,
    'surface': 2,
    'seed': 0,
    'convert': False,
    'create_empty': False,
    'tile': False,
}
