# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  version 2 as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

ptero_colls = [
    'B-',
    'BB',
    'BM',
    'BO',
    'C-',
    'CA',
    'CB',
    'CP',
    'D-',
    'DC',
    'DD',
    'DK',
    'DL',
    'DN',
    'DO',
    'DP',
    'DR',
    'DS',
    'DU',
    'DV',
    'DX',
    'DY',
    'DZ',
    'E-',
    'ED',
    'EZ',
    'F-',
    'FG',
    'FW',
    'FS',
    'FB',
    'FP',
    'FD',
    'FF',
    'FJ',
    'FE',
    'FO',
    'FX',
    'FY',
    'H-',
    'HA',
    'HB',
    'HC',
    'HR',
    'J-',
    'JD',
    'JK',
    'JL',
    'JS',
    'JX',
    'K-',
    'KD',
    'KK',
    'KP',
    'KQ',
    'KR',
    'KS',
    'KX',
    'PP',
    'S-',
    'SO',
    'SZ',
    'T-',
    'TK',
    'TR',
    'TS',
    'TV',
    'TX',
    'TZ',
    'V-',
    'VM',
    'VO',
    'X-',
    'XK',
    'XD',
    'XB',
    'XM',
    'XS',
    'XR',
    'XX',
    'XY',
    'YG',
    'YI',
    'YL',
    'YK',
    'YO',
    'YP',
    'YQ',
    'YV',
    'Z-',
    'ZB',
    'ZO',
    'ZS',
    'ZH',
    'ZL',
    'ZK',
]
