import collections

link_rec = collections.namedtuple\
  ('link_rec', ['dic', 'key', 'obj', 'tag', 'context'])
location_rec = collections.namedtuple\
  ('location_rec', ['context', 'id'])

class linker (object):
  def __init__ (self):
    self.refs = []
    self.ids = []
    self.context = []

  def push_context (self, path):
    self.context.append (path)
  def pop_context (self):
    self.context.pop ()

  def get_ref (self, dic, key, obj, tag):
    """get a reference to an object/tag pair. The reference
       is stored in the dictionary dic under the given key.
    """
    rec = link_rec (dic, key, obj, tag, self.context[-1])
    self.refs.append (rec)
    return (obj, tag)

  def add_id (self, dic, key, obj, tag):
    """add an id definition to the linker.
       The id is stored in the given dictionary under the given
       key and references the obj/tag.
    """
    rec = link_rec (dic, key, obj, tag, self.context[-1])
    self.ids.append (rec)
    return (obj, tag)

  def assign_ids (self):
    """assign all ids. ids within each context will be different.
    """
    context_counts = {}
    locations = {}
    for id in self.ids:
      unique_name = (id.context, id.obj.name, id.tag)
      num_suffix = context_counts.get (unique_name, 0)
      context_counts[unique_name] = num_suffix + 1
      id_name = "%s-%s-%d" % (id.obj.name, id.tag, num_suffix)
      locations[(id.obj, id.tag)] = location_rec (id.context, id_name)
      id.dic[id.key] = id_name
    return locations
  def resolve_refs (self, locs):
    """replace references with their locations.
       The locations are generated by the id assigning process.
    """
    for ref in self.refs:
      print ("have ref: %s, %s" % (ref.obj, ref.tag))
      loc = locs[(ref.obj, ref.tag)]
      if loc.context == ref.context:
        loc_name = "#%s" % (loc.id)
      else:
        loc_name = "%s#%s" % (loc.context, loc.id)
      ref.dic[ref.key] = loc_name
  def resolve (self):
    """resolve all links and replace them with text.
    """
    locs = self.assign_ids ()
    self.resolve_refs (locs)
