# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy,os,re
    
def export(self, context):
    smp = context.scene.smp

    f = open(self.filepath, 'w', encoding='utf-8')
    f.write("--Feature set file\n")
    f.write("--Generated by Enetheru's Blender export script\n\n")
    f.write("local setcfg = {\n\tunitlist = {\n\t},\n\tbuildinglist = {\n\t},\n\tobjectlist = {\n")

    if self.exportType == 'particles':
        for system in context.active_object.particle_systems:
            if system.settings.dupli_object:
                name = system.settings.dupli_object.name
            else:
                name = system.name
            for particle in system.particles:
                f.write("\t\t{ name = '%s', x = %i, z = %i, rot = \"%i\",},\n" %
                    ( name,
                      (particle.location.x + smp.width/2) * 512,
                      (particle.location.y - smp.length/2) * -512,
                      particle.rotation.to_euler().z / 6.141592 * 65536
                    ) )

    if self.exportType == 'selection':
        for obj in bpy.context.selected_objects:
            f.write("\t\t{ name = '%s', x = %i, z = %i, rot = \"%i\",},\n" %
                ( obj.data.name,
                  (obj.location.x + smp.width/2) * 512,
                  (obj.location.y - smp.length/2) * -512,
                  obj.rotation_euler.z / 6.141592 * 65536
                ) )

    f.write("\t},\n}\nreturn setcfg")
    f.close()
    return {'FINISHED'}
