# -*- coding: utf-8 -*-
# This code is generated by addon_translation_tools.
import bpy

translation_dict = {
    "ja_JP": {
        ("*", "Category"): "カテゴリー",
        ("*", "Addon"): "アドオン",
        ("*", "Language"): "言語",
        ("*", "Use text_ctxt"): "text_ctxtを使用",
        ("*", "Label"): "ラベル",
        ("*", "Translation"): "移動",
        ("*", "Relative Path"): "相対パス",
        ("*", "Line Number"): "ライン数",
        ("*", "Keyword Name"): "キーワード名",
        ("*", "Items"): "項目",
        ("*", "Live Edit"): "ライブ編集",
        ("*", "Mode"): "モード",
        ("*", "Standalone"): "スタンドアローン",
        ("*", "Module"): "モジュール",
        ("*", "Name"): "名前",
        ("*", "Version"): "バージョン",
        ("*", "Author"): "制作者",
        ("Operator", "Generate"): "生成",
        ("*", "Output"): "出力",
        ("Operator", "Update"): "更新",
        ("Operator", "Save As"): "名前をつけて保存",
    }
}

if __package__:
    translation_id = __package__
elif __name__ != "__main__":
    translation_id = __name__
else:
    translation_id = __file__

def register(name=None):
    name = name or translation_id
    try:
        bpy.app.translations.register(name, translation_dict)
    except ValueError:
        bpy.app.translations.unregister(name)
        bpy.app.translations.register(name, translation_dict)

def unregister(name=None):
    name = name or translation_id
    bpy.app.translations.unregister(name)

if __name__ == "__main__":
    unregister()
    register()
